rm -f -r	.deps/
rm -f -r	*.moc.cpp
rm -f -r	Makefile
rm -f -r	Makefile.in
rm -f -r	aclocal.m4
rm -f -r	autom4te.cache/
rm -f -r	build-aux/
rm -f -r	config.guess
rm -f -r	config.log
rm -f -r	config.status
rm -f -r	config.sub
rm -f -r	configure
rm -f -r	depcomp
rm -f -r	install-sh
rm -f -r	libtool
rm -f -r	ltmain.sh
rm -f -r	missing
rm -f -r	ui_*.h
rm -f		GITSTR
