# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded sdr::band-data 1.0 [list source [file join $dir band-data.tcl]]
package ifneeded sdr::command 1.0 [list source [file join $dir command.tcl]]
package ifneeded sdr::filter 1.0 [list source [file join $dir filter.tcl]]
package ifneeded sdr::memory 1.0 [list source [file join $dir memory.tcl]]
package ifneeded sdr::servers 1.0 [list source [file join $dir servers.tcl]]
package ifneeded sdr::util 1.0 [list source [file join $dir util.tcl]]
