/********************************************************************************
** Form generated from reading UI file 'Configure.ui'
**
** Created: Thu Jan 3 18:54:30 2013
**      by: Qt User Interface Compiler version 5.0.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_CONFIGURE_H
#define UI_CONFIGURE_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDialog>
#include <QtWidgets/QDialogButtonBox>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Configure
{
public:
    QDialogButtonBox *buttonBox;
    QTabWidget *tabWidget;
    QWidget *Server;
    QLabel *label_6;
    QComboBox *hostComboBox;
    QLabel *label_7;
    QSpinBox *rxSpinBox;
    QPushButton *pBtnAddHost;
    QPushButton *pBtnRemHost;
    QWidget *XVTR;
    QLabel *label_21;
    QLineEdit *minFrequencyLineEdit;
    QLabel *label_22;
    QLineEdit *titleLineEdit;
    QLabel *label_24;
    QLineEdit *maxFrequencyLineEdit;
    QLabel *label_25;
    QLineEdit *ifFrequencyLineEdit;
    QPushButton *addPushButton;
    QPushButton *deletePushButton;
    QTableWidget *XVTRTableWidget;
    QWidget *Audio;
    QComboBox *audioDeviceComboBox;
    QLabel *label_8;
    QComboBox *sampleRateComboBox;
    QLabel *label_9;
    QLabel *label_10;
    QSpinBox *audioChannelsSpinBox;
    QLabel *label_11;
    QComboBox *encodingComboBox;
    QLabel *label_12;
    QComboBox *byteOrderComboBox;
    QLabel *label_28;
    QComboBox *MicComboBox;
    QLabel *label_29;
    QComboBox *MicSampleRateComboBox;
    QLabel *label_30;
    QSpinBox *MicChannelsSpinBox;
    QLabel *label_31;
    QLabel *label_32;
    QComboBox *MicEncodingComboBox;
    QComboBox *MicOrderComboBox;
    QCheckBox *rtpCheckBox;
    QSpinBox *spinBox_cwPitch;
    QLabel *label_cwPitch;
    QWidget *Display;
    QGroupBox *groupBox;
    QLabel *label;
    QLabel *label_2;
    QSpinBox *spectrumHighSpinBox;
    QSpinBox *spectrumLowSpinBox;
    QGroupBox *groupBox_2;
    QLabel *label_3;
    QLabel *label_4;
    QSpinBox *waterfallHighSpinBox;
    QSpinBox *waterfallLowSpinBox;
    QCheckBox *waterfallAutomatic;
    QSpinBox *fpsSpinBox;
    QLabel *label_5;
    QCheckBox *checkBoxWindowPosn;
    QLabel *label_34;
    QSpinBox *avgSpinBox;
    QWidget *DSP;
    QGroupBox *groupBox_3;
    QLabel *label_13;
    QLabel *label_14;
    QLabel *label_15;
    QLabel *label_16;
    QSpinBox *nrTapsSpinBox;
    QSpinBox *nrDelaySpinBox;
    QSpinBox *nrGainSpinBox;
    QSpinBox *nrLeakSpinBox;
    QGroupBox *groupBox_4;
    QLabel *label_17;
    QLabel *label_18;
    QLabel *label_19;
    QLabel *label_20;
    QSpinBox *anfTapsSpinBox;
    QSpinBox *anfDelaySpinBox;
    QSpinBox *anfGainSpinBox;
    QSpinBox *anfLeakSpinBox;
    QGroupBox *groupBox_5;
    QLabel *label_23;
    QSpinBox *nbThresholdSpinBox;
    QLabel *label_26;
    QLabel *label_27;
    QSpinBox *sdromThresholdSpinBox;
    QGroupBox *groupBox_6;
    QCheckBox *RxIQcheckBox;
    QSpinBox *RxIQspinBox;
    QLabel *label_33;
    QCheckBox *RxIQdivCheckBox;
    QWidget *Transmit;
    QCheckBox *allowTx;
    QCheckBox *allowTxOOB;
    QTableWidget *userpass;
    QPushButton *userpasssave;

    void setupUi(QDialog *Configure)
    {
        if (Configure->objectName().isEmpty())
            Configure->setObjectName(QStringLiteral("Configure"));
        Configure->resize(688, 409);
        buttonBox = new QDialogButtonBox(Configure);
        buttonBox->setObjectName(QStringLiteral("buttonBox"));
        buttonBox->setGeometry(QRect(290, 360, 341, 32));
        buttonBox->setOrientation(Qt::Horizontal);
        buttonBox->setStandardButtons(QDialogButtonBox::Close);
        tabWidget = new QTabWidget(Configure);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tabWidget->setGeometry(QRect(0, 0, 631, 361));
        Server = new QWidget();
        Server->setObjectName(QStringLiteral("Server"));
        label_6 = new QLabel(Server);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(36, 28, 41, 17));
        hostComboBox = new QComboBox(Server);
        hostComboBox->setObjectName(QStringLiteral("hostComboBox"));
        hostComboBox->setGeometry(QRect(90, 20, 221, 29));
        hostComboBox->setEditable(true);
        hostComboBox->setInsertPolicy(QComboBox::InsertAtTop);
        label_7 = new QLabel(Server);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(36, 73, 71, 17));
        rxSpinBox = new QSpinBox(Server);
        rxSpinBox->setObjectName(QStringLiteral("rxSpinBox"));
        rxSpinBox->setGeometry(QRect(110, 70, 50, 25));
        rxSpinBox->setMaximum(3);
        pBtnAddHost = new QPushButton(Server);
        pBtnAddHost->setObjectName(QStringLiteral("pBtnAddHost"));
        pBtnAddHost->setGeometry(QRect(210, 70, 101, 27));
        pBtnRemHost = new QPushButton(Server);
        pBtnRemHost->setObjectName(QStringLiteral("pBtnRemHost"));
        pBtnRemHost->setGeometry(QRect(210, 110, 101, 27));
        tabWidget->addTab(Server, QString());
        XVTR = new QWidget();
        XVTR->setObjectName(QStringLiteral("XVTR"));
        XVTR->setEnabled(true);
        label_21 = new QLabel(XVTR);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(180, 20, 141, 17));
        minFrequencyLineEdit = new QLineEdit(XVTR);
        minFrequencyLineEdit->setObjectName(QStringLiteral("minFrequencyLineEdit"));
        minFrequencyLineEdit->setGeometry(QRect(320, 10, 113, 27));
        label_22 = new QLabel(XVTR);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(20, 20, 41, 17));
        titleLineEdit = new QLineEdit(XVTR);
        titleLineEdit->setObjectName(QStringLiteral("titleLineEdit"));
        titleLineEdit->setGeometry(QRect(60, 10, 113, 27));
        label_24 = new QLabel(XVTR);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(440, 20, 41, 17));
        maxFrequencyLineEdit = new QLineEdit(XVTR);
        maxFrequencyLineEdit->setObjectName(QStringLiteral("maxFrequencyLineEdit"));
        maxFrequencyLineEdit->setGeometry(QRect(480, 10, 113, 27));
        label_25 = new QLabel(XVTR);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(180, 60, 121, 17));
        ifFrequencyLineEdit = new QLineEdit(XVTR);
        ifFrequencyLineEdit->setObjectName(QStringLiteral("ifFrequencyLineEdit"));
        ifFrequencyLineEdit->setGeometry(QRect(320, 50, 113, 27));
        addPushButton = new QPushButton(XVTR);
        addPushButton->setObjectName(QStringLiteral("addPushButton"));
        addPushButton->setGeometry(QRect(490, 50, 98, 27));
        deletePushButton = new QPushButton(XVTR);
        deletePushButton->setObjectName(QStringLiteral("deletePushButton"));
        deletePushButton->setGeometry(QRect(540, 260, 81, 27));
        XVTRTableWidget = new QTableWidget(XVTR);
        if (XVTRTableWidget->columnCount() < 4)
            XVTRTableWidget->setColumnCount(4);
        QTableWidgetItem *__qtablewidgetitem = new QTableWidgetItem();
        XVTRTableWidget->setHorizontalHeaderItem(0, __qtablewidgetitem);
        QTableWidgetItem *__qtablewidgetitem1 = new QTableWidgetItem();
        XVTRTableWidget->setHorizontalHeaderItem(1, __qtablewidgetitem1);
        QTableWidgetItem *__qtablewidgetitem2 = new QTableWidgetItem();
        XVTRTableWidget->setHorizontalHeaderItem(2, __qtablewidgetitem2);
        QTableWidgetItem *__qtablewidgetitem3 = new QTableWidgetItem();
        XVTRTableWidget->setHorizontalHeaderItem(3, __qtablewidgetitem3);
        XVTRTableWidget->setObjectName(QStringLiteral("XVTRTableWidget"));
        XVTRTableWidget->setGeometry(QRect(20, 90, 511, 181));
        tabWidget->addTab(XVTR, QString());
        Audio = new QWidget();
        Audio->setObjectName(QStringLiteral("Audio"));
        audioDeviceComboBox = new QComboBox(Audio);
        audioDeviceComboBox->setObjectName(QStringLiteral("audioDeviceComboBox"));
        audioDeviceComboBox->setGeometry(QRect(130, 20, 171, 29));
        label_8 = new QLabel(Audio);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(30, 70, 91, 17));
        sampleRateComboBox = new QComboBox(Audio);
        sampleRateComboBox->setObjectName(QStringLiteral("sampleRateComboBox"));
        sampleRateComboBox->setGeometry(QRect(130, 60, 131, 31));
        label_9 = new QLabel(Audio);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(30, 110, 71, 17));
        label_10 = new QLabel(Audio);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(30, 30, 62, 17));
        audioChannelsSpinBox = new QSpinBox(Audio);
        audioChannelsSpinBox->setObjectName(QStringLiteral("audioChannelsSpinBox"));
        audioChannelsSpinBox->setGeometry(QRect(130, 100, 55, 27));
        audioChannelsSpinBox->setMinimum(1);
        audioChannelsSpinBox->setMaximum(2);
        label_11 = new QLabel(Audio);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(30, 150, 71, 17));
        encodingComboBox = new QComboBox(Audio);
        encodingComboBox->setObjectName(QStringLiteral("encodingComboBox"));
        encodingComboBox->setGeometry(QRect(130, 140, 161, 31));
        label_12 = new QLabel(Audio);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(30, 190, 81, 17));
        byteOrderComboBox = new QComboBox(Audio);
        byteOrderComboBox->setObjectName(QStringLiteral("byteOrderComboBox"));
        byteOrderComboBox->setGeometry(QRect(130, 180, 161, 31));
        label_28 = new QLabel(Audio);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(310, 30, 41, 17));
        MicComboBox = new QComboBox(Audio);
        MicComboBox->setObjectName(QStringLiteral("MicComboBox"));
        MicComboBox->setGeometry(QRect(430, 20, 171, 27));
        label_29 = new QLabel(Audio);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(310, 70, 91, 17));
        MicSampleRateComboBox = new QComboBox(Audio);
        MicSampleRateComboBox->setObjectName(QStringLiteral("MicSampleRateComboBox"));
        MicSampleRateComboBox->setGeometry(QRect(430, 60, 121, 27));
        label_30 = new QLabel(Audio);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(310, 110, 71, 17));
        MicChannelsSpinBox = new QSpinBox(Audio);
        MicChannelsSpinBox->setObjectName(QStringLiteral("MicChannelsSpinBox"));
        MicChannelsSpinBox->setGeometry(QRect(430, 100, 59, 27));
        MicChannelsSpinBox->setMinimum(1);
        MicChannelsSpinBox->setMaximum(2);
        label_31 = new QLabel(Audio);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(310, 190, 81, 17));
        label_32 = new QLabel(Audio);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(310, 150, 71, 17));
        MicEncodingComboBox = new QComboBox(Audio);
        MicEncodingComboBox->setObjectName(QStringLiteral("MicEncodingComboBox"));
        MicEncodingComboBox->setGeometry(QRect(430, 140, 151, 27));
        MicOrderComboBox = new QComboBox(Audio);
        MicOrderComboBox->setObjectName(QStringLiteral("MicOrderComboBox"));
        MicOrderComboBox->setGeometry(QRect(430, 180, 151, 27));
        rtpCheckBox = new QCheckBox(Audio);
        rtpCheckBox->setObjectName(QStringLiteral("rtpCheckBox"));
        rtpCheckBox->setGeometry(QRect(30, 230, 97, 22));
        spinBox_cwPitch = new QSpinBox(Audio);
        spinBox_cwPitch->setObjectName(QStringLiteral("spinBox_cwPitch"));
        spinBox_cwPitch->setGeometry(QRect(230, 220, 59, 29));
        spinBox_cwPitch->setMinimum(400);
        spinBox_cwPitch->setMaximum(1000);
        spinBox_cwPitch->setSingleStep(50);
        spinBox_cwPitch->setValue(600);
        label_cwPitch = new QLabel(Audio);
        label_cwPitch->setObjectName(QStringLiteral("label_cwPitch"));
        label_cwPitch->setGeometry(QRect(150, 230, 69, 19));
        tabWidget->addTab(Audio, QString());
        Display = new QWidget();
        Display->setObjectName(QStringLiteral("Display"));
        groupBox = new QGroupBox(Display);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(20, 10, 291, 101));
        label = new QLabel(groupBox);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(20, 30, 41, 20));
        label_2 = new QLabel(groupBox);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(20, 60, 31, 17));
        spectrumHighSpinBox = new QSpinBox(groupBox);
        spectrumHighSpinBox->setObjectName(QStringLiteral("spectrumHighSpinBox"));
        spectrumHighSpinBox->setGeometry(QRect(60, 30, 81, 21));
        spectrumHighSpinBox->setMinimum(-200);
        spectrumHighSpinBox->setMaximum(200);
        spectrumHighSpinBox->setSingleStep(10);
        spectrumHighSpinBox->setValue(0);
        spectrumLowSpinBox = new QSpinBox(groupBox);
        spectrumLowSpinBox->setObjectName(QStringLiteral("spectrumLowSpinBox"));
        spectrumLowSpinBox->setGeometry(QRect(60, 60, 81, 21));
        spectrumLowSpinBox->setMinimum(-200);
        spectrumLowSpinBox->setMaximum(200);
        spectrumLowSpinBox->setSingleStep(10);
        spectrumLowSpinBox->setValue(-160);
        groupBox_2 = new QGroupBox(Display);
        groupBox_2->setObjectName(QStringLiteral("groupBox_2"));
        groupBox_2->setGeometry(QRect(20, 190, 231, 111));
        label_3 = new QLabel(groupBox_2);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(20, 60, 41, 17));
        label_4 = new QLabel(groupBox_2);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(20, 90, 31, 17));
        waterfallHighSpinBox = new QSpinBox(groupBox_2);
        waterfallHighSpinBox->setObjectName(QStringLiteral("waterfallHighSpinBox"));
        waterfallHighSpinBox->setGeometry(QRect(60, 60, 81, 21));
        waterfallHighSpinBox->setMinimum(-200);
        waterfallHighSpinBox->setMaximum(200);
        waterfallHighSpinBox->setSingleStep(5);
        waterfallHighSpinBox->setValue(-80);
        waterfallLowSpinBox = new QSpinBox(groupBox_2);
        waterfallLowSpinBox->setObjectName(QStringLiteral("waterfallLowSpinBox"));
        waterfallLowSpinBox->setGeometry(QRect(60, 90, 81, 21));
        waterfallLowSpinBox->setMinimum(-200);
        waterfallLowSpinBox->setMaximum(200);
        waterfallLowSpinBox->setSingleStep(5);
        waterfallLowSpinBox->setValue(-120);
        waterfallAutomatic = new QCheckBox(groupBox_2);
        waterfallAutomatic->setObjectName(QStringLiteral("waterfallAutomatic"));
        waterfallAutomatic->setGeometry(QRect(30, 30, 98, 22));
        fpsSpinBox = new QSpinBox(Display);
        fpsSpinBox->setObjectName(QStringLiteral("fpsSpinBox"));
        fpsSpinBox->setGeometry(QRect(80, 100, 50, 21));
        fpsSpinBox->setMinimum(1);
        fpsSpinBox->setMaximum(40);
        fpsSpinBox->setValue(15);
        label_5 = new QLabel(Display);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(40, 100, 31, 17));
        checkBoxWindowPosn = new QCheckBox(Display);
        checkBoxWindowPosn->setObjectName(QStringLiteral("checkBoxWindowPosn"));
        checkBoxWindowPosn->setGeometry(QRect(320, 40, 221, 22));
        checkBoxWindowPosn->setChecked(false);
        label_34 = new QLabel(Display);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(40, 130, 81, 21));
        label_34->setTextFormat(Qt::AutoText);
        avgSpinBox = new QSpinBox(Display);
        avgSpinBox->setObjectName(QStringLiteral("avgSpinBox"));
        avgSpinBox->setGeometry(QRect(120, 130, 59, 27));
        avgSpinBox->setMaximum(20);
        tabWidget->addTab(Display, QString());
        DSP = new QWidget();
        DSP->setObjectName(QStringLiteral("DSP"));
        groupBox_3 = new QGroupBox(DSP);
        groupBox_3->setObjectName(QStringLiteral("groupBox_3"));
        groupBox_3->setGeometry(QRect(20, 10, 181, 141));
        label_13 = new QLabel(groupBox_3);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(20, 27, 62, 17));
        label_14 = new QLabel(groupBox_3);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(20, 57, 62, 17));
        label_15 = new QLabel(groupBox_3);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(20, 87, 62, 17));
        label_16 = new QLabel(groupBox_3);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(20, 117, 62, 17));
        nrTapsSpinBox = new QSpinBox(groupBox_3);
        nrTapsSpinBox->setObjectName(QStringLiteral("nrTapsSpinBox"));
        nrTapsSpinBox->setGeometry(QRect(80, 20, 71, 27));
        nrTapsSpinBox->setMinimum(1);
        nrTapsSpinBox->setMaximum(9999);
        nrTapsSpinBox->setValue(16);
        nrDelaySpinBox = new QSpinBox(groupBox_3);
        nrDelaySpinBox->setObjectName(QStringLiteral("nrDelaySpinBox"));
        nrDelaySpinBox->setGeometry(QRect(80, 50, 71, 27));
        nrDelaySpinBox->setValue(8);
        nrGainSpinBox = new QSpinBox(groupBox_3);
        nrGainSpinBox->setObjectName(QStringLiteral("nrGainSpinBox"));
        nrGainSpinBox->setGeometry(QRect(80, 80, 71, 27));
        nrLeakSpinBox = new QSpinBox(groupBox_3);
        nrLeakSpinBox->setObjectName(QStringLiteral("nrLeakSpinBox"));
        nrLeakSpinBox->setGeometry(QRect(80, 110, 71, 27));
        nrLeakSpinBox->setMinimum(1);
        nrLeakSpinBox->setMaximum(1000);
        nrLeakSpinBox->setValue(10);
        groupBox_4 = new QGroupBox(DSP);
        groupBox_4->setObjectName(QStringLiteral("groupBox_4"));
        groupBox_4->setGeometry(QRect(220, 10, 181, 141));
        label_17 = new QLabel(groupBox_4);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(20, 27, 62, 17));
        label_18 = new QLabel(groupBox_4);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(20, 57, 62, 17));
        label_19 = new QLabel(groupBox_4);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(20, 87, 62, 17));
        label_20 = new QLabel(groupBox_4);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(20, 117, 62, 17));
        anfTapsSpinBox = new QSpinBox(groupBox_4);
        anfTapsSpinBox->setObjectName(QStringLiteral("anfTapsSpinBox"));
        anfTapsSpinBox->setGeometry(QRect(80, 20, 71, 27));
        anfTapsSpinBox->setValue(64);
        anfDelaySpinBox = new QSpinBox(groupBox_4);
        anfDelaySpinBox->setObjectName(QStringLiteral("anfDelaySpinBox"));
        anfDelaySpinBox->setGeometry(QRect(80, 50, 71, 27));
        anfDelaySpinBox->setValue(8);
        anfGainSpinBox = new QSpinBox(groupBox_4);
        anfGainSpinBox->setObjectName(QStringLiteral("anfGainSpinBox"));
        anfGainSpinBox->setGeometry(QRect(80, 80, 71, 27));
        anfGainSpinBox->setMinimum(1);
        anfGainSpinBox->setMaximum(9999);
        anfGainSpinBox->setValue(32);
        anfLeakSpinBox = new QSpinBox(groupBox_4);
        anfLeakSpinBox->setObjectName(QStringLiteral("anfLeakSpinBox"));
        anfLeakSpinBox->setGeometry(QRect(80, 110, 71, 27));
        anfLeakSpinBox->setMinimum(1);
        anfLeakSpinBox->setMaximum(1000);
        groupBox_5 = new QGroupBox(DSP);
        groupBox_5->setObjectName(QStringLiteral("groupBox_5"));
        groupBox_5->setGeometry(QRect(420, 10, 181, 141));
        label_23 = new QLabel(groupBox_5);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(20, 30, 71, 17));
        nbThresholdSpinBox = new QSpinBox(groupBox_5);
        nbThresholdSpinBox->setObjectName(QStringLiteral("nbThresholdSpinBox"));
        nbThresholdSpinBox->setGeometry(QRect(100, 20, 62, 27));
        nbThresholdSpinBox->setMinimum(1);
        nbThresholdSpinBox->setMaximum(200);
        nbThresholdSpinBox->setValue(20);
        label_26 = new QLabel(groupBox_5);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(10, 80, 67, 17));
        QFont font;
        font.setBold(true);
        font.setWeight(75);
        label_26->setFont(font);
        label_27 = new QLabel(groupBox_5);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(20, 110, 71, 17));
        sdromThresholdSpinBox = new QSpinBox(groupBox_5);
        sdromThresholdSpinBox->setObjectName(QStringLiteral("sdromThresholdSpinBox"));
        sdromThresholdSpinBox->setGeometry(QRect(100, 100, 59, 27));
        sdromThresholdSpinBox->setMinimum(1);
        sdromThresholdSpinBox->setMaximum(200);
        sdromThresholdSpinBox->setValue(20);
        groupBox_6 = new QGroupBox(DSP);
        groupBox_6->setObjectName(QStringLiteral("groupBox_6"));
        groupBox_6->setGeometry(QRect(20, 160, 181, 121));
        RxIQcheckBox = new QCheckBox(groupBox_6);
        RxIQcheckBox->setObjectName(QStringLiteral("RxIQcheckBox"));
        RxIQcheckBox->setGeometry(QRect(20, 20, 151, 25));
        RxIQcheckBox->setChecked(true);
        RxIQspinBox = new QSpinBox(groupBox_6);
        RxIQspinBox->setObjectName(QStringLiteral("RxIQspinBox"));
        RxIQspinBox->setGeometry(QRect(90, 80, 59, 29));
        RxIQspinBox->setMinimum(-10);
        RxIQspinBox->setMaximum(100);
        RxIQspinBox->setSingleStep(2);
        RxIQspinBox->setValue(10);
        label_33 = new QLabel(groupBox_6);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(20, 87, 69, 19));
        RxIQdivCheckBox = new QCheckBox(groupBox_6);
        RxIQdivCheckBox->setObjectName(QStringLiteral("RxIQdivCheckBox"));
        RxIQdivCheckBox->setGeometry(QRect(20, 50, 151, 25));
        RxIQdivCheckBox->setChecked(true);
        tabWidget->addTab(DSP, QString());
        Transmit = new QWidget();
        Transmit->setObjectName(QStringLiteral("Transmit"));
        allowTx = new QCheckBox(Transmit);
        allowTx->setObjectName(QStringLiteral("allowTx"));
        allowTx->setGeometry(QRect(30, 20, 141, 22));
        allowTx->setChecked(false);
        allowTxOOB = new QCheckBox(Transmit);
        allowTxOOB->setObjectName(QStringLiteral("allowTxOOB"));
        allowTxOOB->setGeometry(QRect(30, 50, 211, 22));
        userpass = new QTableWidget(Transmit);
        userpass->setObjectName(QStringLiteral("userpass"));
        userpass->setGeometry(QRect(10, 80, 591, 181));
        userpasssave = new QPushButton(Transmit);
        userpasssave->setObjectName(QStringLiteral("userpasssave"));
        userpasssave->setGeometry(QRect(20, 270, 97, 27));
        tabWidget->addTab(Transmit, QString());

        retranslateUi(Configure);
        QObject::connect(buttonBox, SIGNAL(accepted()), Configure, SLOT(accept()));
        QObject::connect(buttonBox, SIGNAL(rejected()), Configure, SLOT(reject()));

        tabWidget->setCurrentIndex(3);


        QMetaObject::connectSlotsByName(Configure);
    } // setupUi

    void retranslateUi(QDialog *Configure)
    {
        Configure->setWindowTitle(QApplication::translate("Configure", "Configure", 0));
        label_6->setText(QApplication::translate("Configure", "Host:", 0));
        label_7->setText(QApplication::translate("Configure", "Receiver:", 0));
        pBtnAddHost->setText(QApplication::translate("Configure", "Add Host", 0));
        pBtnRemHost->setText(QApplication::translate("Configure", "Remove Host", 0));
        tabWidget->setTabText(tabWidget->indexOf(Server), QApplication::translate("Configure", "Server", 0));
        label_21->setText(QApplication::translate("Configure", "Frequency (Hz) Min :", 0));
        label_22->setText(QApplication::translate("Configure", "Title:", 0));
        label_24->setText(QApplication::translate("Configure", "Max :", 0));
        label_25->setText(QApplication::translate("Configure", "IF Frequency(Hz):", 0));
        ifFrequencyLineEdit->setText(QApplication::translate("Configure", "28000000", 0));
        addPushButton->setText(QApplication::translate("Configure", "Add", 0));
        deletePushButton->setText(QApplication::translate("Configure", "Delete", 0));
        QTableWidgetItem *___qtablewidgetitem = XVTRTableWidget->horizontalHeaderItem(0);
        ___qtablewidgetitem->setText(QApplication::translate("Configure", "Title", 0));
        QTableWidgetItem *___qtablewidgetitem1 = XVTRTableWidget->horizontalHeaderItem(1);
        ___qtablewidgetitem1->setText(QApplication::translate("Configure", "Min Frequency", 0));
        QTableWidgetItem *___qtablewidgetitem2 = XVTRTableWidget->horizontalHeaderItem(2);
        ___qtablewidgetitem2->setText(QApplication::translate("Configure", "Max Frequency", 0));
        QTableWidgetItem *___qtablewidgetitem3 = XVTRTableWidget->horizontalHeaderItem(3);
        ___qtablewidgetitem3->setText(QApplication::translate("Configure", "IF Frequency", 0));
        tabWidget->setTabText(tabWidget->indexOf(XVTR), QApplication::translate("Configure", "XVTR", 0));
        label_8->setText(QApplication::translate("Configure", "Sample Rate:", 0));
        label_9->setText(QApplication::translate("Configure", "Channels:", 0));
        label_10->setText(QApplication::translate("Configure", "Device:", 0));
        label_11->setText(QApplication::translate("Configure", "Encoding:", 0));
        label_12->setText(QApplication::translate("Configure", "Byte Order:", 0));
        label_28->setText(QApplication::translate("Configure", "Mic:", 0));
        label_29->setText(QApplication::translate("Configure", "Sample Rate:", 0));
        label_30->setText(QApplication::translate("Configure", "Channels:", 0));
        label_31->setText(QApplication::translate("Configure", "Byte Order:", 0));
        label_32->setText(QApplication::translate("Configure", "Encoding:", 0));
        rtpCheckBox->setText(QApplication::translate("Configure", "Use RTP", 0));
        label_cwPitch->setText(QApplication::translate("Configure", "CW Pitch", 0));
        tabWidget->setTabText(tabWidget->indexOf(Audio), QApplication::translate("Configure", "Audio", 0));
        groupBox->setTitle(QApplication::translate("Configure", "Spectrum", 0));
        label->setText(QApplication::translate("Configure", "High:", 0));
        label_2->setText(QApplication::translate("Configure", "Low:", 0));
        groupBox_2->setTitle(QApplication::translate("Configure", "Waterfall", 0));
        label_3->setText(QApplication::translate("Configure", "High:", 0));
        label_4->setText(QApplication::translate("Configure", "Low:", 0));
        waterfallAutomatic->setText(QApplication::translate("Configure", "Automatic", 0));
        label_5->setText(QApplication::translate("Configure", "FPS:", 0));
        checkBoxWindowPosn->setText(QApplication::translate("Configure", "Save Main Window Geometry", 0));
        label_34->setText(QApplication::translate("Configure", "Averaging:", 0));
        tabWidget->setTabText(tabWidget->indexOf(Display), QApplication::translate("Configure", "Display", 0));
        groupBox_3->setTitle(QApplication::translate("Configure", "NR", 0));
        label_13->setText(QApplication::translate("Configure", "Taps:", 0));
        label_14->setText(QApplication::translate("Configure", "Delay:", 0));
        label_15->setText(QApplication::translate("Configure", "Gain:", 0));
        label_16->setText(QApplication::translate("Configure", "Leak:", 0));
        groupBox_4->setTitle(QApplication::translate("Configure", "ANF", 0));
        label_17->setText(QApplication::translate("Configure", "Taps:", 0));
        label_18->setText(QApplication::translate("Configure", "Delay:", 0));
        label_19->setText(QApplication::translate("Configure", "Gain:", 0));
        label_20->setText(QApplication::translate("Configure", "Leak:", 0));
        groupBox_5->setTitle(QApplication::translate("Configure", "NB", 0));
        label_23->setText(QApplication::translate("Configure", "Threshold:", 0));
        label_26->setText(QApplication::translate("Configure", "NB2", 0));
        label_27->setText(QApplication::translate("Configure", "Threshold:", 0));
        groupBox_6->setTitle(QApplication::translate("Configure", "IQ Correction", 0));
        RxIQcheckBox->setText(QApplication::translate("Configure", "Enabled/Disabled", 0));
        label_33->setText(QApplication::translate("Configure", "RXIQMu", 0));
        RxIQdivCheckBox->setText(QApplication::translate("Configure", "Divide by 100", 0));
        tabWidget->setTabText(tabWidget->indexOf(DSP), QApplication::translate("Configure", "DSP", 0));
        allowTx->setText(QApplication::translate("Configure", "Allow Transmit", 0));
        allowTxOOB->setText(QApplication::translate("Configure", "Allow Transmit out of band", 0));
        userpasssave->setText(QApplication::translate("Configure", "Save", 0));
        tabWidget->setTabText(tabWidget->indexOf(Transmit), QApplication::translate("Configure", "Transmit", 0));
    } // retranslateUi

};

namespace Ui {
    class Configure: public Ui_Configure {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_CONFIGURE_H
