/********************************************************************************
** Form generated from reading UI file 'vfo.ui'
**
** Created: Sun Jan 13 22:02:27 2013
**      by: Qt User Interface Compiler version 5.0.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_VFO_H
#define UI_VFO_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QToolButton>

QT_BEGIN_NAMESPACE

class Ui_vfo
{
public:
    QPushButton *bandBtn_02;
    QToolButton *toolBtnUp;
    QPushButton *bandBtn_10;
    QPushButton *bandBtn_01;
    QPushButton *pBtnBtoA;
    QPushButton *pBtnvfoB;
    QPushButton *pBtnSplit;
    QPushButton *bandBtn_08;
    QPushButton *bandBtn_09;
    QFrame *line_2;
    QToolButton *toolBtnDn;
    QPushButton *pBtnAtoB;
    QPushButton *bandBtn_00;
    QLabel *label_5;
    QPushButton *pBtnScanDn;
    QPushButton *pBtnExch;
    QPushButton *pBtnvfoA;
    QSlider *hSlider;
    QPushButton *pBtnRIT;
    QFrame *frame_2;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_4;
    QLabel *lbl_Amhz;
    QLabel *lbl_Akhz;
    QLabel *lbl_Ahz;
    QLabel *lbl_Bkhz;
    QLabel *lbl_Bmhz;
    QLabel *lbl_Bhz;
    QPushButton *bandBtn_07;
    QPushButton *bandBtn_04;
    QPushButton *pBtnScanUp;
    QPushButton *pBtnSubRx;
    QPushButton *bandBtn_03;
    QPushButton *bandBtn_05;
    QPushButton *bandBtn_06;
    QPushButton *bandBtn_12;
    QPushButton *bandBtn_11;
    QFrame *line;
    QFrame *m6;
    QFrame *m5;
    QFrame *m4;
    QFrame *m3;
    QFrame *m2;
    QFrame *m1;
    QFrame *m0;
    QButtonGroup *btnGrpBand;

    void setupUi(QFrame *vfo)
    {
        if (vfo->objectName().isEmpty())
            vfo->setObjectName(QStringLiteral("vfo"));
        vfo->resize(575, 115);
        vfo->setFrameShape(QFrame::Box);
        vfo->setFrameShadow(QFrame::Raised);
        vfo->setLineWidth(2);
        bandBtn_02 = new QPushButton(vfo);
        btnGrpBand = new QButtonGroup(vfo);
        btnGrpBand->setObjectName(QStringLiteral("btnGrpBand"));
        btnGrpBand->addButton(bandBtn_02);
        bandBtn_02->setObjectName(QStringLiteral("bandBtn_02"));
        bandBtn_02->setGeometry(QRect(519, 7, 51, 25));
        QFont font;
        font.setFamily(QStringLiteral("Droid Sans Mono"));
        font.setPointSize(10);
        bandBtn_02->setFont(font);
        bandBtn_02->setCheckable(true);
        toolBtnUp = new QToolButton(vfo);
        toolBtnUp->setObjectName(QStringLiteral("toolBtnUp"));
        toolBtnUp->setGeometry(QRect(265, 5, 24, 42));
        QFont font1;
        font1.setFamily(QStringLiteral("Droid Sans Mono"));
        toolBtnUp->setFont(font1);
        toolBtnUp->setFocusPolicy(Qt::NoFocus);
        toolBtnUp->setCheckable(false);
        toolBtnUp->setArrowType(Qt::UpArrow);
        bandBtn_10 = new QPushButton(vfo);
        btnGrpBand->addButton(bandBtn_10);
        bandBtn_10->setObjectName(QStringLiteral("bandBtn_10"));
        bandBtn_10->setGeometry(QRect(468, 85, 51, 25));
        bandBtn_10->setFont(font);
        bandBtn_10->setCheckable(true);
        bandBtn_01 = new QPushButton(vfo);
        btnGrpBand->addButton(bandBtn_01);
        bandBtn_01->setObjectName(QStringLiteral("bandBtn_01"));
        bandBtn_01->setGeometry(QRect(468, 7, 51, 25));
        bandBtn_01->setFont(font);
        bandBtn_01->setCheckable(true);
        pBtnBtoA = new QPushButton(vfo);
        pBtnBtoA->setObjectName(QStringLiteral("pBtnBtoA"));
        pBtnBtoA->setGeometry(QRect(353, 7, 53, 25));
        pBtnBtoA->setFont(font);
        pBtnvfoB = new QPushButton(vfo);
        pBtnvfoB->setObjectName(QStringLiteral("pBtnvfoB"));
        pBtnvfoB->setGeometry(QRect(5, 45, 51, 36));
        pBtnvfoB->setFont(font);
        pBtnvfoB->setFocusPolicy(Qt::NoFocus);
        pBtnvfoB->setCheckable(false);
        pBtnvfoB->setChecked(false);
        pBtnSplit = new QPushButton(vfo);
        pBtnSplit->setObjectName(QStringLiteral("pBtnSplit"));
        pBtnSplit->setGeometry(QRect(5, 82, 51, 28));
        pBtnSplit->setFont(font);
        pBtnSplit->setFocusPolicy(Qt::NoFocus);
        pBtnSplit->setStyleSheet(QStringLiteral(""));
        pBtnSplit->setCheckable(false);
        bandBtn_08 = new QPushButton(vfo);
        btnGrpBand->addButton(bandBtn_08);
        bandBtn_08->setObjectName(QStringLiteral("bandBtn_08"));
        bandBtn_08->setGeometry(QRect(519, 59, 51, 25));
        bandBtn_08->setFont(font);
        bandBtn_08->setCheckable(true);
        bandBtn_09 = new QPushButton(vfo);
        btnGrpBand->addButton(bandBtn_09);
        bandBtn_09->setObjectName(QStringLiteral("bandBtn_09"));
        bandBtn_09->setGeometry(QRect(416, 85, 51, 25));
        bandBtn_09->setFont(font);
        bandBtn_09->setCheckable(true);
        line_2 = new QFrame(vfo);
        line_2->setObjectName(QStringLiteral("line_2"));
        line_2->setGeometry(QRect(410, 2, 5, 112));
        line_2->setLineWidth(2);
        line_2->setFrameShape(QFrame::VLine);
        line_2->setFrameShadow(QFrame::Sunken);
        toolBtnDn = new QToolButton(vfo);
        toolBtnDn->setObjectName(QStringLiteral("toolBtnDn"));
        toolBtnDn->setGeometry(QRect(265, 47, 24, 42));
        toolBtnDn->setFont(font1);
        toolBtnDn->setFocusPolicy(Qt::NoFocus);
        toolBtnDn->setArrowType(Qt::DownArrow);
        pBtnAtoB = new QPushButton(vfo);
        pBtnAtoB->setObjectName(QStringLiteral("pBtnAtoB"));
        pBtnAtoB->setGeometry(QRect(300, 7, 52, 25));
        pBtnAtoB->setFont(font);
        bandBtn_00 = new QPushButton(vfo);
        btnGrpBand->addButton(bandBtn_00);
        bandBtn_00->setObjectName(QStringLiteral("bandBtn_00"));
        bandBtn_00->setGeometry(QRect(416, 7, 51, 25));
        bandBtn_00->setFont(font);
        bandBtn_00->setCheckable(true);
        label_5 = new QLabel(vfo);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(130, 90, 51, 20));
        QFont font2;
        font2.setFamily(QStringLiteral("Droid Sans Mono"));
        font2.setPointSize(12);
        label_5->setFont(font2);
        label_5->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        pBtnScanDn = new QPushButton(vfo);
        pBtnScanDn->setObjectName(QStringLiteral("pBtnScanDn"));
        pBtnScanDn->setGeometry(QRect(353, 33, 28, 25));
        pBtnScanDn->setFont(font);
        pBtnScanDn->setCheckable(true);
        pBtnExch = new QPushButton(vfo);
        pBtnExch->setObjectName(QStringLiteral("pBtnExch"));
        pBtnExch->setGeometry(QRect(300, 33, 51, 25));
        pBtnExch->setFont(font);
        pBtnvfoA = new QPushButton(vfo);
        pBtnvfoA->setObjectName(QStringLiteral("pBtnvfoA"));
        pBtnvfoA->setGeometry(QRect(5, 7, 51, 36));
        pBtnvfoA->setFont(font);
        pBtnvfoA->setFocusPolicy(Qt::NoFocus);
        pBtnvfoA->setStyleSheet(QStringLiteral("background-color: rgb(18, 255, 0);"));
        pBtnvfoA->setCheckable(false);
        hSlider = new QSlider(vfo);
        hSlider->setObjectName(QStringLiteral("hSlider"));
        hSlider->setGeometry(QRect(190, 90, 211, 20));
        QFont font3;
        font3.setFamily(QStringLiteral("FreeSans"));
        hSlider->setFont(font3);
        hSlider->setFocusPolicy(Qt::NoFocus);
        hSlider->setMinimum(-1500);
        hSlider->setMaximum(1500);
        hSlider->setSingleStep(25);
        hSlider->setPageStep(25);
        hSlider->setOrientation(Qt::Horizontal);
        pBtnRIT = new QPushButton(vfo);
        pBtnRIT->setObjectName(QStringLiteral("pBtnRIT"));
        pBtnRIT->setGeometry(QRect(300, 59, 52, 25));
        pBtnRIT->setFont(font);
        pBtnRIT->setCheckable(true);
        frame_2 = new QFrame(vfo);
        frame_2->setObjectName(QStringLiteral("frame_2"));
        frame_2->setGeometry(QRect(60, 8, 201, 76));
        QFont font4;
        font4.setKerning(true);
        frame_2->setFont(font4);
        frame_2->setStyleSheet(QStringLiteral("background-color: rgb(210, 255, 206);"));
        frame_2->setFrameShape(QFrame::Panel);
        frame_2->setFrameShadow(QFrame::Sunken);
        frame_2->setLineWidth(3);
        label = new QLabel(frame_2);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(65, 14, 10, 21));
        QFont font5;
        font5.setPointSize(22);
        font5.setBold(true);
        font5.setWeight(75);
        label->setFont(font5);
        label_2 = new QLabel(frame_2);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(134, 8, 10, 30));
        QFont font6;
        font6.setPointSize(20);
        font6.setBold(true);
        font6.setWeight(75);
        label_2->setFont(font6);
        label_3 = new QLabel(frame_2);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setEnabled(false);
        label_3->setGeometry(QRect(65, 49, 10, 21));
        label_3->setFont(font5);
        label_4 = new QLabel(frame_2);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setEnabled(false);
        label_4->setGeometry(QRect(134, 44, 10, 30));
        label_4->setFont(font6);
        lbl_Amhz = new QLabel(frame_2);
        lbl_Amhz->setObjectName(QStringLiteral("lbl_Amhz"));
        lbl_Amhz->setGeometry(QRect(5, 5, 60, 30));
        QFont font7;
        font7.setFamily(QStringLiteral("Droid Sans"));
        font7.setPointSize(26);
        lbl_Amhz->setFont(font7);
        lbl_Amhz->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbl_Akhz = new QLabel(frame_2);
        lbl_Akhz->setObjectName(QStringLiteral("lbl_Akhz"));
        lbl_Akhz->setGeometry(QRect(74, 5, 62, 30));
        QFont font8;
        font8.setFamily(QStringLiteral("Droid Sans"));
        font8.setPointSize(26);
        font8.setBold(false);
        font8.setWeight(50);
        lbl_Akhz->setFont(font8);
        lbl_Akhz->setFocusPolicy(Qt::NoFocus);
        lbl_Akhz->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbl_Ahz = new QLabel(frame_2);
        lbl_Ahz->setObjectName(QStringLiteral("lbl_Ahz"));
        lbl_Ahz->setGeometry(QRect(142, 9, 53, 30));
        QFont font9;
        font9.setFamily(QStringLiteral("Droid Sans"));
        font9.setPointSize(20);
        font9.setItalic(false);
        lbl_Ahz->setFont(font9);
        lbl_Ahz->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbl_Bkhz = new QLabel(frame_2);
        lbl_Bkhz->setObjectName(QStringLiteral("lbl_Bkhz"));
        lbl_Bkhz->setEnabled(false);
        lbl_Bkhz->setGeometry(QRect(74, 42, 62, 30));
        QFont font10;
        font10.setFamily(QStringLiteral("Droid Sans"));
        font10.setPointSize(26);
        font10.setBold(false);
        font10.setItalic(false);
        font10.setWeight(50);
        font10.setStrikeOut(false);
        lbl_Bkhz->setFont(font10);
        lbl_Bkhz->setFocusPolicy(Qt::NoFocus);
        lbl_Bkhz->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbl_Bmhz = new QLabel(frame_2);
        lbl_Bmhz->setObjectName(QStringLiteral("lbl_Bmhz"));
        lbl_Bmhz->setEnabled(false);
        lbl_Bmhz->setGeometry(QRect(5, 42, 60, 30));
        QFont font11;
        font11.setFamily(QStringLiteral("Droid Sans"));
        font11.setPointSize(26);
        font11.setItalic(false);
        font11.setStrikeOut(false);
        lbl_Bmhz->setFont(font11);
        lbl_Bmhz->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lbl_Bhz = new QLabel(frame_2);
        lbl_Bhz->setObjectName(QStringLiteral("lbl_Bhz"));
        lbl_Bhz->setEnabled(false);
        lbl_Bhz->setGeometry(QRect(142, 45, 53, 30));
        QFont font12;
        font12.setFamily(QStringLiteral("Droid Sans"));
        font12.setPointSize(20);
        font12.setItalic(false);
        font12.setStrikeOut(false);
        lbl_Bhz->setFont(font12);
        lbl_Bhz->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        bandBtn_07 = new QPushButton(vfo);
        btnGrpBand->addButton(bandBtn_07);
        bandBtn_07->setObjectName(QStringLiteral("bandBtn_07"));
        bandBtn_07->setGeometry(QRect(468, 59, 51, 25));
        bandBtn_07->setFont(font);
        bandBtn_07->setCheckable(true);
        bandBtn_04 = new QPushButton(vfo);
        btnGrpBand->addButton(bandBtn_04);
        bandBtn_04->setObjectName(QStringLiteral("bandBtn_04"));
        bandBtn_04->setGeometry(QRect(468, 33, 51, 25));
        bandBtn_04->setFont(font);
        bandBtn_04->setCheckable(true);
        pBtnScanUp = new QPushButton(vfo);
        pBtnScanUp->setObjectName(QStringLiteral("pBtnScanUp"));
        pBtnScanUp->setGeometry(QRect(380, 33, 28, 25));
        pBtnScanUp->setFont(font);
        pBtnScanUp->setCheckable(true);
        pBtnSubRx = new QPushButton(vfo);
        pBtnSubRx->setObjectName(QStringLiteral("pBtnSubRx"));
        pBtnSubRx->setGeometry(QRect(60, 85, 51, 25));
        pBtnSubRx->setFont(font);
        pBtnSubRx->setCheckable(true);
        bandBtn_03 = new QPushButton(vfo);
        btnGrpBand->addButton(bandBtn_03);
        bandBtn_03->setObjectName(QStringLiteral("bandBtn_03"));
        bandBtn_03->setGeometry(QRect(416, 33, 51, 25));
        bandBtn_03->setFont(font);
        bandBtn_03->setCheckable(true);
        bandBtn_05 = new QPushButton(vfo);
        btnGrpBand->addButton(bandBtn_05);
        bandBtn_05->setObjectName(QStringLiteral("bandBtn_05"));
        bandBtn_05->setGeometry(QRect(519, 33, 51, 25));
        bandBtn_05->setFont(font);
        bandBtn_05->setCheckable(true);
        bandBtn_06 = new QPushButton(vfo);
        btnGrpBand->addButton(bandBtn_06);
        bandBtn_06->setObjectName(QStringLiteral("bandBtn_06"));
        bandBtn_06->setGeometry(QRect(416, 59, 51, 25));
        bandBtn_06->setFont(font);
        bandBtn_06->setCheckable(true);
        bandBtn_12 = new QPushButton(vfo);
        btnGrpBand->addButton(bandBtn_12);
        bandBtn_12->setObjectName(QStringLiteral("bandBtn_12"));
        bandBtn_12->setGeometry(QRect(353, 59, 53, 25));
        bandBtn_12->setFont(font);
        bandBtn_12->setCheckable(true);
        bandBtn_11 = new QPushButton(vfo);
        btnGrpBand->addButton(bandBtn_11);
        bandBtn_11->setObjectName(QStringLiteral("bandBtn_11"));
        bandBtn_11->setGeometry(QRect(519, 85, 51, 25));
        bandBtn_11->setFont(font);
        bandBtn_11->setCheckable(true);
        line = new QFrame(vfo);
        line->setObjectName(QStringLiteral("line"));
        line->setGeometry(QRect(294, 2, 5, 80));
        line->setLineWidth(2);
        line->setFrameShape(QFrame::VLine);
        line->setFrameShadow(QFrame::Sunken);
        m6 = new QFrame(vfo);
        m6->setObjectName(QStringLiteral("m6"));
        m6->setGeometry(QRect(113, 82, 5, 5));
        QPalette palette;
        QBrush brush(QColor(255, 255, 255, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(0, 0, 0, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette.setBrush(QPalette::Active, QPalette::Light, brush1);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush1);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush1);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette.setBrush(QPalette::Active, QPalette::AlternateBase, brush1);
        QBrush brush2(QColor(255, 255, 220, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ToolTipBase, brush2);
        palette.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        m6->setPalette(palette);
        m6->setFrameShape(QFrame::VLine);
        m6->setFrameShadow(QFrame::Sunken);
        m5 = new QFrame(vfo);
        m5->setObjectName(QStringLiteral("m5"));
        m5->setGeometry(QRect(148, 82, 5, 5));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Light, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Midlight, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Mid, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush);
        palette1.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette1.setBrush(QPalette::Active, QPalette::AlternateBase, brush1);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipBase, brush2);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Light, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Midlight, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Mid, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Light, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Midlight, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Mid, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        m5->setPalette(palette1);
        m5->setFrameShape(QFrame::VLine);
        m5->setFrameShadow(QFrame::Sunken);
        m4 = new QFrame(vfo);
        m4->setObjectName(QStringLiteral("m4"));
        m4->setGeometry(QRect(167, 82, 5, 5));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette2.setBrush(QPalette::Active, QPalette::Light, brush1);
        palette2.setBrush(QPalette::Active, QPalette::Midlight, brush1);
        palette2.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette2.setBrush(QPalette::Active, QPalette::Mid, brush1);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush);
        palette2.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette2.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette2.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette2.setBrush(QPalette::Active, QPalette::AlternateBase, brush1);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipBase, brush2);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::Light, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::Midlight, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::Mid, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Light, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Midlight, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Mid, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush2);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        m4->setPalette(palette2);
        m4->setFrameShape(QFrame::VLine);
        m4->setFrameShadow(QFrame::Sunken);
        m3 = new QFrame(vfo);
        m3->setObjectName(QStringLiteral("m3"));
        m3->setGeometry(QRect(185, 82, 5, 5));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette3.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Active, QPalette::Light, brush1);
        palette3.setBrush(QPalette::Active, QPalette::Midlight, brush1);
        palette3.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette3.setBrush(QPalette::Active, QPalette::Mid, brush1);
        palette3.setBrush(QPalette::Active, QPalette::Text, brush);
        palette3.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette3.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette3.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette3.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette3.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette3.setBrush(QPalette::Active, QPalette::AlternateBase, brush1);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipBase, brush2);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Light, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Midlight, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Mid, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Light, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Midlight, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Mid, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        m3->setPalette(palette3);
        m3->setFrameShape(QFrame::VLine);
        m3->setFrameShadow(QFrame::Sunken);
        m2 = new QFrame(vfo);
        m2->setObjectName(QStringLiteral("m2"));
        m2->setGeometry(QRect(217, 82, 5, 5));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette4.setBrush(QPalette::Active, QPalette::Light, brush1);
        palette4.setBrush(QPalette::Active, QPalette::Midlight, brush1);
        palette4.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette4.setBrush(QPalette::Active, QPalette::Mid, brush1);
        palette4.setBrush(QPalette::Active, QPalette::Text, brush);
        palette4.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette4.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette4.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette4.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette4.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette4.setBrush(QPalette::Active, QPalette::AlternateBase, brush1);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipBase, brush2);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::Light, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::Midlight, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::Mid, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::Light, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::Midlight, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::Mid, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush2);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        m2->setPalette(palette4);
        m2->setFrameShape(QFrame::VLine);
        m2->setFrameShadow(QFrame::Sunken);
        m1 = new QFrame(vfo);
        m1->setObjectName(QStringLiteral("m1"));
        m1->setGeometry(QRect(231, 82, 5, 5));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette5.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette5.setBrush(QPalette::Active, QPalette::Light, brush1);
        palette5.setBrush(QPalette::Active, QPalette::Midlight, brush1);
        palette5.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette5.setBrush(QPalette::Active, QPalette::Mid, brush1);
        palette5.setBrush(QPalette::Active, QPalette::Text, brush);
        palette5.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette5.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette5.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette5.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette5.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette5.setBrush(QPalette::Active, QPalette::AlternateBase, brush1);
        palette5.setBrush(QPalette::Active, QPalette::ToolTipBase, brush2);
        palette5.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::Light, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::Midlight, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::Mid, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Light, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Midlight, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Mid, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush2);
        palette5.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        m1->setPalette(palette5);
        m1->setFrameShape(QFrame::VLine);
        m1->setFrameShadow(QFrame::Sunken);
        m0 = new QFrame(vfo);
        m0->setObjectName(QStringLiteral("m0"));
        m0->setGeometry(QRect(245, 82, 5, 5));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette6.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette6.setBrush(QPalette::Active, QPalette::Light, brush1);
        palette6.setBrush(QPalette::Active, QPalette::Midlight, brush1);
        palette6.setBrush(QPalette::Active, QPalette::Dark, brush1);
        palette6.setBrush(QPalette::Active, QPalette::Mid, brush1);
        palette6.setBrush(QPalette::Active, QPalette::Text, brush);
        palette6.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette6.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette6.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette6.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette6.setBrush(QPalette::Active, QPalette::Shadow, brush1);
        palette6.setBrush(QPalette::Active, QPalette::AlternateBase, brush1);
        palette6.setBrush(QPalette::Active, QPalette::ToolTipBase, brush2);
        palette6.setBrush(QPalette::Active, QPalette::ToolTipText, brush1);
        palette6.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette6.setBrush(QPalette::Inactive, QPalette::Light, brush1);
        palette6.setBrush(QPalette::Inactive, QPalette::Midlight, brush1);
        palette6.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette6.setBrush(QPalette::Inactive, QPalette::Mid, brush1);
        palette6.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette6.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette6.setBrush(QPalette::Inactive, QPalette::Shadow, brush1);
        palette6.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush1);
        palette6.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush2);
        palette6.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::Light, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::Midlight, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::Mid, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::Shadow, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush2);
        palette6.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush1);
        m0->setPalette(palette6);
        m0->setFrameShape(QFrame::VLine);
        m0->setFrameShadow(QFrame::Sunken);

        retranslateUi(vfo);
        QObject::connect(hSlider, SIGNAL(valueChanged(int)), label_5, SLOT(setNum(int)));

        QMetaObject::connectSlotsByName(vfo);
    } // setupUi

    void retranslateUi(QFrame *vfo)
    {
        vfo->setWindowTitle(QApplication::translate("vfo", "Frame", 0));
        bandBtn_02->setText(QApplication::translate("vfo", "60", 0));
        toolBtnUp->setText(QApplication::translate("vfo", "...", 0));
        bandBtn_10->setText(QApplication::translate("vfo", "6", 0));
        bandBtn_01->setText(QApplication::translate("vfo", "80", 0));
        pBtnBtoA->setText(QApplication::translate("vfo", "B->A", 0));
        pBtnvfoB->setText(QApplication::translate("vfo", "VFO B", 0));
        pBtnvfoB->setShortcut(QApplication::translate("vfo", "B", 0));
        pBtnSplit->setText(QApplication::translate("vfo", "Split", 0));
        bandBtn_08->setText(QApplication::translate("vfo", "12", 0));
        bandBtn_09->setText(QApplication::translate("vfo", "10", 0));
        toolBtnDn->setText(QApplication::translate("vfo", "...", 0));
        pBtnAtoB->setText(QApplication::translate("vfo", "A->B", 0));
        bandBtn_00->setText(QApplication::translate("vfo", "160", 0));
        label_5->setText(QApplication::translate("vfo", "0", 0));
        pBtnScanDn->setText(QApplication::translate("vfo", "<Sc", 0));
        pBtnExch->setText(QApplication::translate("vfo", "A<>B", 0));
        pBtnvfoA->setText(QApplication::translate("vfo", "VFO A", 0));
        pBtnvfoA->setShortcut(QApplication::translate("vfo", "A", 0));
        pBtnRIT->setText(QApplication::translate("vfo", "RIT", 0));
        pBtnRIT->setShortcut(QApplication::translate("vfo", "R", 0));
        label->setText(QApplication::translate("vfo", ".", 0));
        label_2->setText(QApplication::translate("vfo", ",", 0));
        label_3->setText(QApplication::translate("vfo", ".", 0));
        label_4->setText(QApplication::translate("vfo", ",", 0));
        lbl_Amhz->setText(QApplication::translate("vfo", "999", 0));
        lbl_Akhz->setText(QApplication::translate("vfo", "919", 0));
        lbl_Ahz->setText(QApplication::translate("vfo", "919", 0));
        lbl_Bkhz->setText(QApplication::translate("vfo", "919", 0));
        lbl_Bmhz->setText(QApplication::translate("vfo", "999", 0));
        lbl_Bhz->setText(QApplication::translate("vfo", "919", 0));
        bandBtn_07->setText(QApplication::translate("vfo", "15", 0));
        bandBtn_04->setText(QApplication::translate("vfo", "30", 0));
        pBtnScanUp->setText(QApplication::translate("vfo", "an>", 0));
        pBtnSubRx->setText(QApplication::translate("vfo", "subRx", 0));
        pBtnSubRx->setShortcut(QApplication::translate("vfo", "S", 0));
        bandBtn_03->setText(QApplication::translate("vfo", "40", 0));
        bandBtn_05->setText(QApplication::translate("vfo", "20", 0));
        bandBtn_06->setText(QApplication::translate("vfo", "17", 0));
        bandBtn_12->setText(QApplication::translate("vfo", "WWV", 0));
        bandBtn_11->setText(QApplication::translate("vfo", "GEN", 0));
    } // retranslateUi

};

namespace Ui {
    class vfo: public Ui_vfo {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_VFO_H
